server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /productSearches/**
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/shippings/**, 
        - id: inventory
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**, 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=/customers/**, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, /orderStatuses/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /productSearches/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/shippings/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /orderStatuses/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
            - Path=/orders/** 
            - Path=/shippings/** 
            - Path=/inventories/** 
            - Path=/customers/** 
            - Path= 
            - Path=/orders/** 
            - Path=/shippings/** 
            - Path=/inventories/** 
            - Path=/customers/** 
            - Path= 
